FROM openjdk:17-jdk-slim

MAINTAINER LABEL onkar2701.com

COPY /target/loans-micro-service-0.0.1-SNAPSHOT.jar loans-micro-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","loans-micro-service-0.0.1-SNAPSHOT.jar"]
