FROM openjdk:17-jdk-slim

MAINTAINER LABEL onkar2701.com

COPY /target/cards-micro-service-0.0.1-SNAPSHOT.jar cards-micro-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","cards-micro-service-0.0.1-SNAPSHOT.jar"]